TES-189: Functionality to add tests to collections
HansGabriel/TestTrek pull request #165
Opened 2023-10-15 17:49 UTC by HansGabriel

# Description

1. Should have a button in the specific collection screen to add tests
2. You can browse all public tests and add them to the collection
3. Should be able to remove a test from a collection

2023-10-15 21:38 UTC, EdmelKun requested changes

2023-10-15 21:38 UTC, EdmelKun commented on apps/expo/src/forms/CreateTestForm/index.tsx
> -type FormProps = SetOptional<Omitted, "collection">;
Please remove unusued imports

2023-10-16 03:32 UTC, HansGabriel commented on apps/expo/src/forms/CreateTestForm/index.tsx
> -type FormProps = SetOptional<Omitted, "collection">;
Sure

2023-10-16 06:43 UTC, EdmelKun approved these changes

2023-10-16 06:49 UTC, 3LL4N approved these changes

2023-10-16 06:49 UTC, merged