TES-281: Refactor Create Question Screen
HansGabriel/TestTrek pull request #250
Opened 2023-12-10 15:43 UTC by HansGabriel

# Description

- Don't allow to change question, create question, and exit "Create Question" screen if current question is not saved or is incorrect validation
- Change exit prompt for test edit to canceling or exit and discarding changes

## Code Snippets

N/A

## Screenshots/Images

https://github.com/HansGabriel/TestTrek/assets/49836841/05845a27-018f-456f-a535-eb2a506543c1

# How Has This Been Tested?

Locally tested

2023-12-10 18:00 UTC, EdmelKun requested changes

2023-12-10 18:00 UTC, EdmelKun commented on apps/expo/src/forms/CreateTestForm/index.tsx
> +                Question {questions.length > 0 ? `(${questions.length})` : "()"}
Hide if there are no created questions

2023-12-10 18:00 UTC, EdmelKun commented on apps/expo/src/forms/CreateTestForm/index.tsx
> +                  View All
Same also here. Hide when there are no questions

2023-12-10 18:00 UTC, EdmelKun commented on apps/expo/src/screens/create-question/index.tsx
> +            const isValidInput = handleSaveQuestion({
User would be stuck in create question screen since user is forced to fill out the fields. Make sure that user has a way to exit the create question screen

2023-12-11 05:27 UTC, HansGabriel commented on apps/expo/src/forms/CreateTestForm/index.tsx
> +                Question {questions.length > 0 ? `(${questions.length})` : "()"}
Good catch

2023-12-11 14:58 UTC, EdmelKun requested changes

2023-12-11 14:58 UTC, EdmelKun commented on apps/expo/src/forms/CreateTestForm/index.tsx
> +                <FlashList
Returns warning that says "FlashList's rendered size is not usable. Please make sure that the parent view of the list has a valid size."

2023-12-11 17:20 UTC, EdmelKun approved these changes

2023-12-11 17:20 UTC, merged