jetdieron01/tes 83
HansGabriel/TestTrek pull request #79
Opened 2023-09-19 17:24 UTC by 3LL4N

# Description

Added View All functionality to all home screen sections

## Screenshots/Images

https://github.com/HansGabriel/TestTrek/assets/70251380/24c18ac5-66dc-4371-a216-38784ad3571b

2023-09-19 20:34 UTC, EdmelKun requested changes

2023-09-19 20:34 UTC, EdmelKun commented on apps/expo/src/components/top-collections/TopCollectionsHomeSection.tsx
>        <FlatList
Top collections not centered. Try putting "self-center" on parent container

2023-09-19 20:34 UTC, EdmelKun commented on apps/expo/src/components/top-collections/TopCollectionsHomeSection.tsx
>        <FlatList
![379403156_985348625870987_4131119955113242148_n](https://github.com/HansGabriel/TestTrek/assets/68092712/52db7e3f-e80b-4231-8d92-88bd32200b64)

2023-09-20 00:15 UTC, HansGabriel commented on apps/expo/src/components/view-all-display/tests/ViewAllTestDisplay.tsx
> +  let headerTitle = "";
kinda problematic to use let since it's mutable, can you use ts-pattern for pattern matching instead? https://github.com/gvergnaud/ts-pattern

2023-09-20 00:20 UTC, HansGabriel approved these changes
Code-wise would want changes but ok na lng for now

2023-09-20 02:13 UTC, EdmelKun approved these changes

2023-09-20 02:15 UTC, merged